<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration: create_medical_reviews_table
 *
 * The final medical opinion record, written by a licensed doctor.
 * This table has a strict 1:1 relationship with `mcu_registrations`.
 *
 * AI Copilot fields:
 *  - `ai_summary`            → raw markdown text from Gemini
 *  - `ai_recommended_status` → Gemini's suggested fitness status
 *
 * Doctor override fields:
 *  - `doctor_conclusion`     → free-text clinical conclusion
 *  - `doctor_notes`          → additional notes / follow-up instructions
 *  - `final_status`          → the legally binding fitness determination
 *  - `reviewed_by`           → FK to the doctor's user record
 *  - `reviewed_at`           → timestamp of doctor's approval/sign-off
 *
 * `review_status` tracks the workflow state:
 *   PENDING → AI job running or doctor hasn't reviewed yet
 *   AI_DRAFT_READY → Gemini returned a draft, awaiting doctor
 *   REVIEWED → Doctor has submitted final_status
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('medical_reviews', function (Blueprint $table) {
            $table->id();

            $table->foreignId('registration_id')
                  ->unique()   // enforce 1:1 with mcu_registrations
                  ->constrained('mcu_registrations')
                  ->cascadeOnDelete();

            // ── AI Copilot Fields ──────────────────────────────────────────
            $table->longText('ai_summary')->nullable()
                  ->comment('Structured markdown summary generated by Gemini AI');

            $table->enum('ai_recommended_status', [
                'FIT TO WORK',
                'FIT WITH NOTE',
                'TEMPORARY UNFIT',
                'UNFIT',
            ])->nullable()->comment('Gemini\'s suggested fitness classification');

            // ── Doctor Override Fields ─────────────────────────────────────
            $table->text('doctor_conclusion')->nullable()
                  ->comment('Doctor\'s free-text clinical conclusion');

            $table->text('doctor_notes')->nullable()
                  ->comment('Follow-up instructions, referrals, restrictions');

            $table->enum('final_status', [
                'FIT TO WORK',
                'FIT WITH NOTE',
                'TEMPORARY UNFIT',
                'UNFIT',
            ])->nullable()->index()
              ->comment('Legally binding fitness determination by the doctor');

            $table->foreignId('reviewed_by')
                  ->nullable()
                  ->constrained('users')
                  ->nullOnDelete()
                  ->comment('The licensed doctor who approved this review');

            $table->timestamp('reviewed_at')
                  ->nullable()
                  ->comment('Timestamp of doctor\'s digital sign-off');

            // ── Workflow State ─────────────────────────────────────────────
            $table->enum('review_status', ['PENDING', 'AI_DRAFT_READY', 'REVIEWED'])
                  ->default('PENDING')
                  ->index()
                  ->comment('Tracks AI + doctor workflow stages');

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('medical_reviews');
    }
};
