<?php

declare(strict_types=1);

namespace App\Filament\Resources;

use App\Filament\Resources\MedicalReviewResource\Pages;
use App\Models\MedicalReview;
use App\Models\User;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Infolists\Components\BadgeEntry;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * MedicalReviewResource
 *
 * Filament v5 Resource — designed specifically for the Doctor's workflow.
 *
 * The doctor sees:
 *  1. A queue of registrations with AI_DRAFT_READY status.
 *  2. The full AI-generated summary rendered as Markdown.
 *  3. Input fields to write their own clinical conclusion.
 *  4. A final "Approve & Sign" action that stamps reviewed_at.
 *
 * Design Principles:
 *  - Read-heavy: doctor reviews and rarely creates. Create is handled by the AI job.
 *  - `->poll('15s')` is applied ONLY on the list page when the status filter is
 *    PENDING (waiting for AI), not globally — avoids unnecessary server load.
 *  - The edit form is split into AI Draft (read-only) and Doctor Input (editable)
 *    sections using `->disabled()` on AI fields.
 *  - `->live(onBlur: true)` on all doctor-input selects.
 */
class MedicalReviewResource extends Resource
{
    protected static ?string $model = MedicalReview::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-magnifying-glass';

    protected static ?string $navigationGroup = 'Medical';

    protected static ?int $navigationSort = 20;

    protected static ?string $navigationLabel = 'Medical Reviews';

    protected static ?string $modelLabel = 'Medical Review';

    protected static ?string $pluralModelLabel = 'Medical Reviews';

    // ── Form ──────────────────────────────────────────────────────────────

    /**
     * The form is used for the Edit page only (doctor fills in conclusion).
     * The AI-generated fields are shown as disabled read-only inputs to provide
     * context without allowing edits.
     */
    public static function form(Form $form): Form
    {
        return $form->schema([

            // ── Registration Context (read-only) ──────────────────────────
            Forms\Components\Section::make('Patient & Registration')
                ->icon('heroicon-o-user')
                ->columns(3)
                ->collapsed(false)
                ->schema([
                    Forms\Components\Placeholder::make('patient_name')
                        ->label('Patient Name')
                        ->content(fn (?MedicalReview $record) =>
                            $record?->registration?->patient?->name ?? '—'
                        ),

                    Forms\Components\Placeholder::make('patient_risk')
                        ->label('Job Risk Level')
                        ->content(fn (?MedicalReview $record) =>
                            $record?->registration?->patient?->job_risk_level ?? '—'
                        ),

                    Forms\Components\Placeholder::make('barcode')
                        ->label('Barcode')
                        ->content(fn (?MedicalReview $record) =>
                            $record?->registration?->barcode_code ?? '—'
                        ),

                    Forms\Components\Placeholder::make('patient_department')
                        ->label('Department')
                        ->content(fn (?MedicalReview $record) =>
                            $record?->registration?->patient?->department ?? '—'
                        ),

                    Forms\Components\Placeholder::make('patient_job_title')
                        ->label('Job Title')
                        ->content(fn (?MedicalReview $record) =>
                            $record?->registration?->patient?->job_title ?? '—'
                        ),

                    Forms\Components\Placeholder::make('patient_age')
                        ->label('Age / Gender')
                        ->content(fn (?MedicalReview $record) => implode(' / ', array_filter([
                            $record?->registration?->patient?->age
                                ? $record->registration->patient->age . ' years'
                                : null,
                            $record?->registration?->patient?->gender,
                        ])) ?: '—'),
                ]),

            // ── AI Copilot Draft (read-only) ──────────────────────────────
            Forms\Components\Section::make('🤖 AI Copilot Draft')
                ->description('Generated by Gemini AI. Review carefully before approving.')
                ->icon('heroicon-o-cpu-chip')
                ->collapsible()
                ->schema([

                    /**
                     * AI summary is displayed as a Markdown viewer using
                     * Filament's MarkdownEditor in disabled/preview mode.
                     * This gives rich formatting without allowing edits.
                     *
                     * We use Textarea (disabled) instead of MarkdownEditor
                     * because it is lighter on cPanel resources.
                     */
                    Forms\Components\Textarea::make('ai_summary')
                        ->label('AI Summary')
                        ->disabled()
                        ->rows(15)
                        ->columnSpanFull()
                        ->hint('Read-only — AI generated clinical summary')
                        ->extraAttributes([
                            'class' => 'font-mono text-sm bg-gray-50 dark:bg-gray-900',
                        ]),

                    Forms\Components\Select::make('ai_recommended_status')
                        ->label('AI Recommended Status')
                        ->disabled()
                        ->options([
                            'FIT TO WORK'     => '✅ Fit to Work',
                            'FIT WITH NOTE'   => '⚠️ Fit with Note',
                            'TEMPORARY UNFIT' => '🔶 Temporary Unfit',
                            'UNFIT'           => '❌ Unfit',
                        ])
                        ->columnSpanFull(),
                ]),

            // ── Abnormal Results Summary ──────────────────────────────────
            Forms\Components\Section::make('⚠️ Abnormal Findings')
                ->description('Items flagged as outside normal range.')
                ->icon('heroicon-o-exclamation-triangle')
                ->collapsible()
                ->collapsed(false)
                ->schema([
                    Forms\Components\Placeholder::make('abnormal_results_list')
                        ->label('')
                        ->content(function (?MedicalReview $record): \Illuminate\Support\HtmlString {
                            if (!$record?->registration_id) {
                                return new \Illuminate\Support\HtmlString('<em>No registration loaded.</em>');
                            }

                            $abnormalResults = \App\Models\McuResult::query()
                                ->where('registration_id', $record->registration_id)
                                ->where('is_abnormal', true)
                                ->with('item:id,name,item_code,unit,normal_min,normal_max,input_type,normal_text')
                                ->get();

                            if ($abnormalResults->isEmpty()) {
                                return new \Illuminate\Support\HtmlString(
                                    '<p class="text-green-600 font-medium">✅ No abnormal findings.</p>'
                                );
                            }

                            $rows = $abnormalResults->map(function (\App\Models\McuResult $r) {
                                $normalRange = $r->item?->normal_range_display ?? 'N/A';
                                $unit = $r->item?->unit ?? '';
                                $value = "{$r->result_value} {$unit}";

                                return "<tr class='border-b'>
                                    <td class='py-1 pr-4 font-mono text-xs text-gray-500'>{$r->item?->item_code}</td>
                                    <td class='py-1 pr-4 font-medium'>{$r->item?->name}</td>
                                    <td class='py-1 pr-4 text-red-600 font-bold'>{$value}</td>
                                    <td class='py-1 text-gray-500 text-sm'>{$normalRange}</td>
                                </tr>";
                            })->implode('');

                            return new \Illuminate\Support\HtmlString(
                                "<table class='w-full text-sm'>
                                    <thead class='text-left text-gray-400 text-xs uppercase'>
                                        <tr>
                                            <th class='pb-2'>Code</th>
                                            <th class='pb-2'>Test Name</th>
                                            <th class='pb-2'>Result</th>
                                            <th class='pb-2'>Normal Range</th>
                                        </tr>
                                    </thead>
                                    <tbody>{$rows}</tbody>
                                </table>"
                            );
                        })
                        ->columnSpanFull(),
                ]),

            // ── Doctor Input Section ──────────────────────────────────────
            Forms\Components\Section::make('🩺 Doctor\'s Clinical Assessment')
                ->description('Complete this section to approve the medical review.')
                ->icon('heroicon-o-pencil-square')
                ->schema([

                    /**
                     * Doctor's conclusion — free-text, required before approval.
                     * `->live(onBlur: true)` defers Livewire updates until the
                     * doctor moves focus away from the textarea.
                     */
                    Forms\Components\Textarea::make('doctor_conclusion')
                        ->label('Clinical Conclusion')
                        ->required()
                        ->rows(5)
                        ->placeholder('Write your clinical assessment based on the examination results and AI draft above...')
                        ->live(onBlur: true)
                        ->hint('This will appear in the patient\'s medical certificate.')
                        ->columnSpanFull()
                        ->disabled(fn (?MedicalReview $record) =>
                            $record?->review_status === 'REVIEWED'
                        ),

                    Forms\Components\Textarea::make('doctor_notes')
                        ->label('Doctor\'s Notes & Recommendations')
                        ->rows(4)
                        ->placeholder('Additional notes, work restrictions, referrals, follow-up schedule...')
                        ->live(onBlur: true)
                        ->columnSpanFull()
                        ->disabled(fn (?MedicalReview $record) =>
                            $record?->review_status === 'REVIEWED'
                        ),

                    /**
                     * Final status selector — the legally binding field.
                     * Defaults to the AI recommendation but doctor can override.
                     * `->live(onBlur: true)` keeps the form responsive.
                     *
                     * AI recommended status is shown as a hint to guide the doctor
                     * without forcing them to follow it.
                     */
                    Forms\Components\Select::make('final_status')
                        ->label('Final Fitness Status')
                        ->required()
                        ->options([
                            'FIT TO WORK'     => '✅ Fit to Work',
                            'FIT WITH NOTE'   => '⚠️ Fit with Note',
                            'TEMPORARY UNFIT' => '🔶 Temporary Unfit',
                            'UNFIT'           => '❌ Unfit',
                        ])
                        ->live(onBlur: true)
                        ->hint(fn (?MedicalReview $record) =>
                            $record?->ai_recommended_status
                                ? "AI recommends: {$record->ai_recommended_status}"
                                : 'Select the final fitness determination'
                        )
                        ->disabled(fn (?MedicalReview $record) =>
                            $record?->review_status === 'REVIEWED'
                        ),

                    /**
                     * Review status — shown only to admins for manual override.
                     * Normally set automatically by the approve action.
                     */
                    Forms\Components\Select::make('review_status')
                        ->label('Review Status')
                        ->options([
                            'PENDING'        => 'Pending',
                            'AI_DRAFT_READY' => 'AI Draft Ready',
                            'REVIEWED'       => 'Reviewed',
                        ])
                        ->live(onBlur: true)
                        ->visible(fn () => auth()->user()?->hasRole('super_admin'))
                        ->disabled(fn (?MedicalReview $record) =>
                            $record?->review_status === 'REVIEWED'
                        ),

                    // Reviewed_by and reviewed_at are set programmatically
                    Forms\Components\Hidden::make('reviewed_by'),
                    Forms\Components\Hidden::make('reviewed_at'),
                ]),
        ]);
    }

    // ── Table ─────────────────────────────────────────────────────────────

    public static function table(Table $table): Table
    {
        return $table
            /**
             * Eager loading — prevent N+1 on the review list.
             * registration.patient → needed for name, department, risk display
             * registration.project → needed for project/org context
             * reviewer             → needed for "reviewed by" column
             */
            ->modifyQueryUsing(fn (Builder $query) =>
                $query->with([
                    'registration:id,patient_id,project_id,barcode_code,status',
                    'registration.patient:id,name,employee_id,department,job_risk_level',
                    'registration.project:id,name,organization_id',
                    'registration.project.organization:id,name',
                    'reviewer:id,name',
                ])
                ->latest()
            )

            ->columns([
                Tables\Columns\TextColumn::make('registration.barcode_code')
                    ->label('Barcode')
                    ->searchable()
                    ->copyable()
                    ->fontFamily('mono'),

                Tables\Columns\TextColumn::make('registration.patient.name')
                    ->label('Patient')
                    ->description(fn (MedicalReview $r) =>
                        "[{$r->registration?->patient?->employee_id}] — {$r->registration?->patient?->department}"
                    )
                    ->searchable(['patients.name', 'patients.employee_id']),

                Tables\Columns\BadgeColumn::make('registration.patient.job_risk_level')
                    ->label('Risk')
                    ->colors([
                        'success' => 'LOW',
                        'warning' => 'MEDIUM',
                        'danger'  => 'HIGH',
                        'gray'    => 'EXTREME',
                    ]),

                Tables\Columns\TextColumn::make('registration.project.name')
                    ->label('Project')
                    ->description(fn (MedicalReview $r) =>
                        $r->registration?->project?->organization?->name
                    )
                    ->searchable()
                    ->toggleable(),

                Tables\Columns\BadgeColumn::make('review_status')
                    ->label('Status')
                    ->colors([
                        'gray'    => 'PENDING',
                        'info'    => 'AI_DRAFT_READY',
                        'success' => 'REVIEWED',
                    ]),

                Tables\Columns\BadgeColumn::make('ai_recommended_status')
                    ->label('AI Says')
                    ->colors([
                        'success' => 'FIT TO WORK',
                        'warning' => 'FIT WITH NOTE',
                        'danger'  => 'TEMPORARY UNFIT',
                        'gray'    => 'UNFIT',
                    ])
                    ->default('—'),

                Tables\Columns\BadgeColumn::make('final_status')
                    ->label('Final Status')
                    ->colors([
                        'success' => 'FIT TO WORK',
                        'warning' => 'FIT WITH NOTE',
                        'danger'  => 'TEMPORARY UNFIT',
                        'gray'    => 'UNFIT',
                    ])
                    ->placeholder('—'),

                Tables\Columns\TextColumn::make('reviewer.name')
                    ->label('Reviewed By')
                    ->placeholder('Pending')
                    ->toggleable(),

                Tables\Columns\TextColumn::make('reviewed_at')
                    ->label('Reviewed At')
                    ->dateTime('d M Y H:i')
                    ->sortable()
                    ->placeholder('—')
                    ->toggleable(),
            ])

            ->filters([
                Tables\Filters\SelectFilter::make('review_status')
                    ->label('Review Status')
                    ->options([
                        'PENDING'        => 'Pending (AI Processing)',
                        'AI_DRAFT_READY' => 'AI Draft Ready (Doctor Action Required)',
                        'REVIEWED'       => 'Reviewed (Finalized)',
                    ]),

                Tables\Filters\SelectFilter::make('final_status')
                    ->label('Final Status')
                    ->options([
                        'FIT TO WORK'     => 'Fit to Work',
                        'FIT WITH NOTE'   => 'Fit with Note',
                        'TEMPORARY UNFIT' => 'Temporary Unfit',
                        'UNFIT'           => 'Unfit',
                    ]),

                Tables\Filters\SelectFilter::make('reviewed_by')
                    ->label('Doctor')
                    ->relationship('reviewer', 'name')
                    ->searchable()
                    ->preload(false),
            ])

            ->actions([
                Tables\Actions\ViewAction::make(),

                /**
                 * Primary doctor action: opens the edit form for filling in
                 * the clinical assessment and approving the review.
                 */
                Tables\Actions\EditAction::make()
                    ->label(fn (MedicalReview $r) =>
                        $r->review_status === 'REVIEWED' ? 'View Review' : 'Review & Approve'
                    )
                    ->icon(fn (MedicalReview $r) =>
                        $r->review_status === 'REVIEWED'
                            ? 'heroicon-o-eye'
                            : 'heroicon-o-pencil-square'
                    )
                    ->color(fn (MedicalReview $r) =>
                        $r->review_status === 'AI_DRAFT_READY' ? 'success' : 'gray'
                    ),

                /**
                 * One-click "Approve" quick action — uses the AI recommendation
                 * as default and prompts the doctor to confirm. For doctors who
                 * agree with the AI draft and want a fast workflow.
                 */
                Tables\Actions\Action::make('quick_approve')
                    ->label('Quick Approve')
                    ->icon('heroicon-o-check-badge')
                    ->color('success')
                    ->visible(fn (MedicalReview $r) =>
                        $r->review_status === 'AI_DRAFT_READY'
                        && $r->ai_recommended_status !== null
                    )
                    ->form([
                        Forms\Components\Select::make('final_status')
                            ->label('Final Fitness Status')
                            ->required()
                            ->options([
                                'FIT TO WORK'     => '✅ Fit to Work',
                                'FIT WITH NOTE'   => '⚠️ Fit with Note',
                                'TEMPORARY UNFIT' => '🔶 Temporary Unfit',
                                'UNFIT'           => '❌ Unfit',
                            ])
                            ->default(fn (MedicalReview $r) => $r->ai_recommended_status),

                        Forms\Components\Textarea::make('doctor_conclusion')
                            ->label('Clinical Conclusion')
                            ->required()
                            ->rows(4)
                            ->placeholder('Confirm AI assessment or provide your own conclusion...'),

                        Forms\Components\Textarea::make('doctor_notes')
                            ->label('Notes (Optional)')
                            ->rows(3),
                    ])
                    ->modalHeading('Quick Approve Medical Review')
                    ->modalDescription('AI recommendation will be used as the default status. You can override below.')
                    ->modalSubmitActionLabel('Approve & Sign')
                    ->action(function (MedicalReview $record, array $data) {
                        $record->update([
                            'final_status'       => $data['final_status'],
                            'doctor_conclusion'  => $data['doctor_conclusion'],
                            'doctor_notes'       => $data['doctor_notes'] ?? null,
                            'reviewed_by'        => auth()->id(),
                            'reviewed_at'        => now(),
                            'review_status'      => 'REVIEWED',
                        ]);

                        \Filament\Notifications\Notification::make()
                            ->title('Medical review approved.')
                            ->body("Final status: {$data['final_status']}")
                            ->success()
                            ->send();
                    }),
            ])

            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])

            ->defaultSort('updated_at', 'desc')
            ->striped()
            ->paginated([10, 25, 50]);
    }

    // ── Pages ─────────────────────────────────────────────────────────────

    public static function getPages(): array
    {
        return [
            'index'  => Pages\ListMedicalReviews::route('/'),
            'view'   => Pages\ViewMedicalReview::route('/{record}'),
            'edit'   => Pages\EditMedicalReview::route('/{record}/edit'),
        ];
    }

    /**
     * Restrict access: only doctors, super_admins, and org_admins
     * should see this resource in the navigation.
     */
    public static function shouldRegisterNavigation(): bool
    {
        return auth()->user()?->hasAnyRole(['super_admin', 'org_admin', 'doctor']) ?? false;
    }

    /**
     * Query scoping: doctors only see reviews for their organization's patients.
     * Super admins see all.
     */
    public static function getEloquentQuery(): Builder
    {
        $query = parent::getEloquentQuery();
        $user = auth()->user();

        if ($user->hasRole('super_admin')) {
            return $query;
        }

        // Scope to the doctor's organization
        if ($user->organization_id) {
            $query->whereHas('registration.project', fn (Builder $q) =>
                $q->where('organization_id', $user->organization_id)
            );
        }

        return $query;
    }
}
